### ISSUE TITLE
Feature Request: edit of Stats command

### ISSUE THREAD

**Issue by Kamixe1999** [yakirarage/UndertaleRPG#10]
### What feature would you like to see added/changed?

Attack and Defence stats.

### Detailed description of your feature request?

Attack and Defence stats should be added to the /stats command so it's an easier option to see those stats than right when you battle someone.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this will be added in the next update.

ty for suggesting! ❤
