### ISSUE TITLE
Bug Report: Snowdin Consumables Prices. Episode 2.

### ISSUE THREAD

**Issue by Kamixe1999** [yakirarage/UndertaleRPG#13]
### What Feature do you want to report a bug for?

Incorrect healing values.

### Detailed description of the bug you wish to report?

As the shop describes in Snowdin, Pies should heal 10, Nice Cream - 15, And the Snowman Piece - 45.
And it is indeed displayed like that on the shop. However, upon further testing, all those items heal only 24. No matter what.
The values should be fixed, or well, at least the Nice Cream and Snowman piece. Pies could potentially stay at 24, given that their price will also be edited, alongside the shop description.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this has been fixed ty for reporting it
