### ISSUE TITLE
Feature Request: Papyrus boss fight.

### ISSUE THREAD

**Issue by Kamixe1999** [yakirarage/UndertaleRPG#14]
### What feature would you like to see added/changed?

Boss fights in Snowdin.

### Detailed description of your feature request?

Currently, the Dog Couple are the only boss fight in Snowdin. However, I can bet that me alongside others, would prefer to fight Papyrus as well.
Is he going to be added soon, perhaps as a second boss of Snowdin that you will be able to fight after defeating the Dog Couple?

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is already in the bot.
