### ISSUE TITLE
Bug Report: Boss "softlock"

### ISSUE THREAD

**Issue by Kamixe1999** [yakirarage/UndertaleRPG#15]
### What Feature do you want to report a bug for?

Turns breaking in a Boss Fight.

### Detailed description of the bug you wish to report?

While a solution is there, in a form of dismissing the message and using /boss again, you can get softlocked.
If you use Mercy, and it will be rejected, the next turn will have you softlocked, unable to either attack or spare again.
Found it out as I was checking if you could get a different boss.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is fixed is the next update.

ty for reporting! ❤
