### ISSUE TITLE
ACT Suggestion 

### ISSUE THREAD

**Issue by ChickenYT33** [yakirarage/UndertaleRPG#16]
### What feature would you like to see added/changed?

I'd like to see ACT in fight! Example for we can check how much ATK DEF nad monsters description!

### Detailed description of your feature request?

[ACT] - ACT Button.

After pressing that, you will see this:

[CHECK] - Check enemy's stats.

[Option depends on enemy like Complient and Threat on Froggit.]

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
please explain further... you are already able to see the stats of the monster you a fighting.
