### ISSUE TITLE
Bug Report: Defense don't work

### ISSUE THREAD

**Issue by Gamemodeguest1** [yakirarage/UndertaleRPG#20]
### What Feature do you want to report a bug for?

Defense

### Detailed description of the bug you wish to report?

In battle when monster damages me, he damages the exact amount of attack he has, and ignores all my defense, with my defense turns into the same amount as my attack has.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

That makes armor useless and a waste of gold.

**Comment by yakirarage** [comment]
this is not implemented yet so it is not a bug.
