### ISSUE TITLE
Readd the u?intro feature please!

### ISSUE THREAD

**Issue by samia-2006** [yakirarage/UndertaleRPG#24]
### What feature would you like to see added/changed?

u?intro

### Detailed description of your feature request?

Like the old bot, you do u?intro and it'll introduce you to the world of undertale.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this will be added with the next update ty for the suggestion
