### ISSUE TITLE
Spares count are always on 1.

### ISSUE THREAD

**Issue by ChickenYT33** [yakirarage/UndertaleRPG#26]
### What Feature do you want to report a bug for?

Spares count

### Detailed description of the bug you wish to report?

Spares count are always on 1.
Make it unlimited for leaderboard.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
fixed in the next update. ty for reporting!

**Comment by ChickenYT33** [comment]
Your welcome. (Btw this is my email, im Chicken that sent that issue.)

Dne ne 29. 1. 2023 21:42 uživatel Yara Naafs ***@***.***>
napsal:
