### ISSUE TITLE
Bug Report: Defense

### ISSUE THREAD

**Issue by Gamemodeguest1** [yakirarage/UndertaleRPG#27]
### What Feature do you want to report a bug for?

Defense

### Detailed description of the bug you wish to report?

How does stat Defence work? Shouldn't it decrease damage? Cuz instead it does nothing, doing all the armor in bot useless...

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

This thing exists long time ago.

**Comment by yakirarage** [comment]
it does nothing cus it is not a feature. read around before reporting.
