### ISSUE TITLE
Feature Request: (Sell items)

### ISSUE THREAD

**Issue by racoono** [yakirarage/UndertaleRPG#29]
### What feature would you like to see added/changed?

Sell button or /sell command

### Detailed description of your feature request?

Going to your inventory which is what we do most on fights and seeing the old items we used are quiet confusing and possibly use it in accident. it will also bring us more space for our inventory
with the sell button would feel like in rpg if its in the /shop
could also put /sell than putting it on the shop.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is already a thing just type in /sell
