### ISSUE TITLE
Bug Report: Defense does nothing

### ISSUE THREAD

**Issue by NotFlappyBox** [yakirarage/UndertaleRPG#3]
### What Feature do you want to report a bug for?

Undertale RPG bot

### Detailed description of the bug you wish to report?

In the new Undertale RPG bot, you will take the same amount of damage no matter how much defense you have.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
it is currently only there for a future update
