### ISSUE TITLE
/booster does not work

### ISSUE THREAD

**Issue by super-br** [yakirarage/UndertaleRPG#32]
### What Feature do you want to report a bug for?

/booster command

### Detailed description of the bug you wish to report?

The /booster command doesn't detect the boost, so it does not work

### terms & Privicy

- [x] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this has been fixed. ty for reporting
