### ISSUE TITLE
broken stats and items (Bug)

### ISSUE THREAD

**Issue by flamingblitzshard** [yakirarage/UndertaleRPG#35]
### What Feature do you want to report a bug for?

the defense stat and equippment items don't work

### Detailed description of the bug you wish to report?

Just like I explained in the report- thing- the defense stat doesn't work, I'm in the ruins currently and Vegitoids are destroying me with they're 10 damage even though I have 7 defense and the faded ribbon ( btw items(equipment, not healing, healing works) don't even work ), and when you die and your LV is above 1, you don't get restored to full HP. only 20.
![image](https://user-images.githubusercontent.com/128243470/226117760-f747d812-afea-4cba-81c9-79cf4f590d5d.png)

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is not a bug like said many many times the defense system has not been added yet so please can all of you stop bugging me about it

**Comment by flamingblitzshard** [comment]
I also listed a few more bugs there,-

**Comment by yakirarage** [comment]
yes and none of them are a bug. let me dump it down a bit

on death you restore 20hp not your max i made it like that on purpose would be to op if it was max

defense is not yet a system it might never be if people keep fucking bugging me about a system that is clearly not in place

**Comment by flamingblitzshard** [comment]
alright- alright-- sorry-
