### ISSUE TITLE
Bug Report:snowdin bosses

### ISSUE THREAD

**Issue by flamingblitzshard** [yakirarage/UndertaleRPG#36]
### What Feature do you want to report a bug for?

only 1 snowdin boss can be done

### Detailed description of the bug you wish to report?

There are more then 1 snowdin boss, yet only one of them can be done ( I killed dogi already and wanted to get papyrus but I can't because of the 1 boss limit-)
![image](https://user-images.githubusercontent.com/128243470/229002832-70a517e4-25a2-41b5-a63b-f243d6568d4a.png)
![image](https://user-images.githubusercontent.com/128243470/229002877-996e6ee7-f2dc-477f-9863-5a886a509188.png)

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is not a bug. i indented it this way if you think it is better differently make a suggestion not a bug report

**Comment by flamingblitzshard** [comment]
wait- then where did papyrus go after I defeated dogi?-

**Comment by yakirarage** [comment]
> wait- then where did papyrus go after I defeated dogi?-

i programmed the bot so you can only fight 1 of the 2 bosses

**Comment by flamingblitzshard** [comment]
'ah- alrighty,
