### ISSUE TITLE
Bug Report: Sell mechanic. [Broken function.]

### ISSUE THREAD

**Issue by Kamixe1999** [yakirarage/UndertaleRPG#41]
### What Feature do you want to report a bug for?

The new Sell mechanic.

### Detailed description of the bug you wish to report?

Right, so. When I sold some stuff, I checked on my gold. And it was only 199. Later I sold one Faded ribbon for '75' G and bought 2 S. Pieces (20 G for both combined). Then I also defeated Ice Cap and got 33 G. I checked stats again, and now I only had 88 G. I decided to sell one S. Piece for testing. It ended up making my gold go all the way to 10 G.
Conclusion: Somehow, in some way, the Sell mechanic takes Gold instead of giving it to you. In fact, it takes more than the item's worth. That means if someone sells things, while they are making more space, they're paying for it. Quite literally.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this has been fixed thank you for reporting
