### ISSUE TITLE
Bug Report: (fill in)

### ISSUE THREAD

**Issue by Aidan612** [yakirarage/UndertaleRPG#42]
### What Feature do you want to report a bug for?

Resets 

### Detailed description of the bug you wish to report?

When i reset I get the same xp and gold when I should be getting a 1.40x boost xp and a 1.20 times boost in gold
![ABEFBECB-584F-4F73-8D3F-998352B12E53](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/077e256a-4dce-43a9-a48a-f9c425c46bc3)
![D3A2A06A-BC51-456C-92A2-72F6C83CB0BD](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/f76183e4-ae24-4b6e-b78e-a27f15a13b2d)
![3DC8015A-ECF8-4BDC-B84F-AB13BF1ABF24](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/f5dad666-6206-489c-91e0-24e4a829f1be)
![4E1FC254-4863-4024-A1D6-45624C4215E8](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/14e5d8cb-b19a-4cf6-a8c6-f4bb5b3d796e)

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

In case it didn’t send 
![E22FFC7D-3E65-4382-B53A-D2E79A2D408D](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/f4e52421-823c-470c-90bd-c3ab3098722d)
![579194BE-9C8E-47B5-BEBA-09B88EAA058D](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/9941ab3b-ed6c-482f-8676-11ea139f2307)
![EBE8E146-D117-4E0E-A259-1474C3A3E438](https://github.com/Undertale-RPG/Undertale-RPG/assets/137429993/ba44169f-1705-4960-8eb2-e6bc7a872081)
Fix it pls and thank you

**Comment by yakirarage** [comment]
should be fixed in the next update thx for reporting!
