### ISSUE TITLE
Bug Report: (Spider Donut)

### ISSUE THREAD

**Issue by DiiioBrando** [yakirarage/UndertaleRPG#44]
### What Feature do you want to report a bug for?

Spider Donut

### Detailed description of the bug you wish to report?

Restores only 12 health, although it is written that it restores 17.

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

![Screenshot_20230916-181418_Discord~2](https://github.com/Undertale-RPG/Undertale-RPG/assets/102269032/47da25df-0d1a-4ced-a6d5-42ea82c1e9fe)

**Comment by yakirarage** [comment]
this will be fixed in the next update
