### ISSUE TITLE
Feature Request: (fill in)

### ISSUE THREAD

**Issue by HamSans** [yakirarage/UndertaleRPG#45]
### What feature would you like to see added/changed?

Making healing more specific

### Detailed description of your feature request?

If you use a consumable, it should say your current hp alongside with the item's name
ex: You used a spider cider, you have 32/36 hp!

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
will be done with next update
