### ISSUE TITLE
Bug Report: (/use command not work again)

### ISSUE THREAD

**Issue by yohlroenzoitno** [yakirarage/UndertaleRPG#5]
### What Feature do you want to report a bug for?

/use command not work

### Detailed description of the bug you wish to report?

other commands work, but only this one doesn't

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by NotFlappyBox** [comment]
This is probably because you have more than 25 items. Currently there is no way you can get rid of the items once you are in this state. I believe that this might be caused since by the limit of 25 buttons in a single message.

**Comment by yakirarage** [comment]
this will be fixed with the new update.

ty for reporting! ❤
